apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-resale-api
  namespace: vehicle-resale
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8082"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - vehicle-resale-api
              topologyKey: topology.kubernetes.io/zone

