apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vehicle-resale

bases:
  - ../../base

namePrefix: azure-

patchesStrategicMerge:
  - ingress-patch.yaml
  - pvc-patch.yaml

resources:
  - storageclass.yaml

replicas:
  - name: vehicle-resale-api
    count: 2

commonAnnotations:
  environment: azure
  cloud-provider: azure
  managed-by: kustomize

