apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: vehicle-resale-backend-config
  namespace: vehicle-resale
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8082
    type: HTTP
    requestPath: /health/ready
  connectionDraining:
    drainingTimeoutSec: 60
  timeoutSec: 30
  logging:
    enable: true
    sampleRate: 1.0

