apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vehicle-resale

bases:
  - ../../base

namePrefix: gcp-

patchesStrategicMerge:
  - ingress-patch.yaml
  - pvc-patch.yaml

resources:
  - storageclass.yaml
  - backendconfig.yaml

replicas:
  - name: vehicle-resale-api
    count: 2

commonAnnotations:
  environment: gcp
  cloud-provider: gcp
  managed-by: kustomize

